[project]
name = "signal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.10.1",
    "signalbot>=0.16.0",
    "python-dotenv>=1.0.0",
]
